#!/bin/bash
PROFILE=$1
PATH_TO_MAIN_PROJECT=$2
COMMON_FOLDER=ERICnrnsa
SOURCES_FOLDER_NAME=src
SOURCES_COMMON_FOLDER=../$COMMON_FOLDER/$SOURCES_FOLDER_NAME
TARGET_LINK_FOLDER=../build/$PROFILE


if [ -e $SOURCES_FOLDER_NAME ]; then
   rm -rf $SOURCES_FOLDER_NAME
fi

ln -s $SOURCES_COMMON_FOLDER $SOURCES_FOLDER_NAME
exit 0
